name: xhimera1311
version: '1.3.1.1'
summary: Wallet and Deamon for Xhimera Coin
description: |
This is a compilation of XHimera Wallet for VPS that use Ubuntu 16.04, and to complite this on VPS take so long.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  prepare:
    plugin: nil
      prepare: |
        echo "deb http://ppa.launchpad.net/bitcoin/bitcoin/ubuntu xenial main" | sudo tee -a /etc/apt/sources.list
        echo "deb-src http://ppa.launchpad.net/bitcoin/bitcoin/ubuntu xenial main" | sudo tee -a /etc/apt/sources.list 
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys D46F45428842CE5E
        apt update
        apt upgrade -yy
    plugin: make
      build-packages:
        - build-essential 
        - libtool 
        - autotools-dev 
        - autoconf
        - pkg-config 
        - libssl-dev
        - software-properties-common
        - libdb4.8-dev 
        - libdb4.8++-dev
        - libboost-all-dev
        - libminiupnpc-dev
        - libevent-dev
        - git
        - automake
